apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  namespace: nodeapp
spec:
  selector:
    app: nodeapp
  ports:
  - protocol: TCP
    port: 80          
    targetPort: 6041  
    nodePort: 30041
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  namespace: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: 773651758893.dkr.ecr.ap-south-1.amazonaws.com/nodeapp:latest
        ports:
        - containerPort: 6041
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "60m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nodeapp-hpa
  namespace: nodeapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodeapp
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
